lib/catcasts_web/router.ex
defmodule CatcastsWeb.Router do
  use CatcastsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Catcasts.Plugs.SetUser
  end

  pipeline :auth do
    plug CatcastsWeb.Plugs.RequireAuth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CatcastsWeb do
    pipe_through [:browser, :auth]

    resources "/videos", VideoController, only: [:new, :create, :delete]
  end

  scope "/", CatcastsWeb do
    pipe_through :browser

    resources "/videos", VideoController, only: [:index, :show]
    get "/", PageController, :index
  end

  scope "/auth", CatcastsWeb do
    pipe_through :browser

    get "/signout", SessionController, :delete
    get "/:provider", SessionController, :request
    get "/:provider/callback", SessionController, :create
  end

  # Other scopes may use custom stacks.
  # scope "/api", CatcastsWeb do
  #   pipe_through :api
  # end
end

lib/catcasts_web/views/layout_view.ex
defmodule CatcastsWeb.LayoutView do
  use CatcastsWeb, :view
end

lib/catcasts_web/templates/layout/_navigation.html.eex
<nav class="flex items-center justify-between flex-wrap bg-gray-200 p-3 font-sans">
  <div class="flex items-center flex-shrink-0 text-gray-900 mr-6">
    <span class="font-semibold text-xl tracking-tighter">Catcasts</span>
  </div>
  <div class="block lg:hidden">
    <button class="flex items-center px-3 py-2 border rounded text-gray-900 border-gray-900" onclick="navbarAccordian()">
      <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
    </button>
  </div>
  <div class="hidden w-full block flex-grow lg:flex lg:items-center lg:w-auto" id="nav">
    <div class="text-sm lg:flex-grow"></div>
    <div>
      <%= if @conn.assigns[:user] do %>
        <span class="block mt-4 lg:inline-block lg:mt-0 text-grey-900 mr-4">
          Welcome, <%= @conn.assigns.user.first_name %>!
        </span>
        <%= link "Videos", to: Routes.video_path(@conn, :index), class: "block mt-4 lg:inline-block lg:mt-0 text-gray-900 mr-4 hover:underline" %>
        <%= link "Add video", to: Routes.video_path(@conn, :new), class: "block mt-4 lg:inline-block lg:mt-0 text-gray-900 mr-4 hover:underline" %>
        <%= link "Sign out", to: Routes.session_path(@conn, :delete), class: "block mt-4 lg:inline-block lg:mt-0 text-gray-900 mr-4 hover:underline" %>
      <% else %>
        <%= link "Videos", to: Routes.video_path(@conn, :index), class: "block mt-4 lg:inline-block lg:mt-0 text-gray-900 mr-4 hover:underline" %>
        <a href="/auth/google?scope=email%20profile" class="block mt-4 lg:inline-block lg:mt-0 text-gray-900 mr-4 hover:underline">
          Sign in with Google
        </a>
      <% end %>
    </div>
  </div>
  <script>
    function navbarAccordian() {
      var x = document.getElementById("nav");
      x.classList.toggle("hidden");
    }
  </script>
</nav>

lib/catcasts_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Catcasts</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <%= render "_navigation.html", conn: @conn %>
    <main role="main">
      <p class="alert bg-blue-100 border border-blue-400 text-blue-600 px-4 py-3 rounded relative" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert bg-red-100 border border-red-400 text-red-600 px-4 py-3 rounded relative" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>